// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkflmppcjqrcqdeemali.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrZmxtcHBjanFyY3FkZWVtYWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTYwMTEsImV4cCI6MjA2MDM3MjAxMX0.inuvqcn-BCTDRUSv6zlDWBaMYQY8yE5wa4AaQrDoMdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);